import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { supabase } from "@/lib/supabase-browser";

export const Route = createFileRoute("/reset-password")({ component: ResetPasswordPage });

function ResetPasswordPage(){
 const navigate=useNavigate(); const [password,setPassword]=useState(""); const [confirm,setConfirm]=useState(""); const [message,setMessage]=useState(""); const [ready,setReady]=useState(false);
 useEffect(()=>{if(!supabase)return;supabase.auth.getSession().then(({data})=>setReady(Boolean(data.session)));},[]);
 async function submit(e:React.FormEvent){e.preventDefault();setMessage("");if(password.length<8){setMessage("Password must be at least 8 characters.");return}if(password!==confirm){setMessage("Passwords do not match.");return}if(!supabase){setMessage("Authentication is not configured.");return}const {error}=await supabase.auth.updateUser({password});if(error)setMessage(error.message);else{setMessage("Password updated. Opening the factory…");setTimeout(()=>void navigate({to:"/digital-products"}),500);}}
 return <main className="flex min-h-screen items-center justify-center bg-[#07080a] px-5 text-white"><div className="w-full max-w-md rounded-3xl border border-white/10 bg-white/[0.03] p-7"><div className="text-xs font-semibold uppercase tracking-[0.25em] text-emerald-400">ResoFit Digital Factory</div><h1 className="mt-3 text-2xl font-semibold">Set new password</h1><p className="mt-2 text-sm text-white/50">{ready?"Choose a new password for your account.":"Open this page from the recovery link sent to your email."}</p>{ready?<form onSubmit={submit} className="mt-6 space-y-3"><input required minLength={8} type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="New password (8+ characters)" autoComplete="new-password" className="w-full rounded-xl border border-white/10 bg-black/30 px-3 py-3 text-sm outline-none"/><input required minLength={8} type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} placeholder="Confirm new password" autoComplete="new-password" className="w-full rounded-xl border border-white/10 bg-black/30 px-3 py-3 text-sm outline-none"/><button className="w-full rounded-xl bg-white px-4 py-3 text-sm font-semibold text-black">Update password</button></form>:<Link to="/login" className="mt-6 block text-center text-sm text-emerald-300">Return to sign in</Link>}{message&&<p className="mt-4 rounded-xl border border-amber-400/20 bg-amber-400/5 p-3 text-xs text-amber-200">{message}</p>}</div></main>;
}
