import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useState } from "react";
import { supabase } from "@/lib/supabase-browser";

export const Route = createFileRoute("/signup")({ component: SignupPage });

function SignupPage(){
 const navigate=useNavigate(); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [confirm,setConfirm]=useState(""); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false);
 async function submit(e:React.FormEvent){e.preventDefault();setMessage("");if(password.length<8){setMessage("Password must be at least 8 characters.");return}if(password!==confirm){setMessage("Passwords do not match.");return}if(!supabase){setMessage("Authentication is not configured.");return}setBusy(true);const {data,error}=await supabase.auth.signUp({email:email.trim().toLowerCase(),password,options:{emailRedirectTo:window.location.origin+"/digital-products"}});if(error)setMessage(error.message);else if(data.session)await navigate({to:"/digital-products"});else setMessage("Account created. Check your email to confirm your account, then sign in.");setBusy(false);}
 return <main className="flex min-h-screen items-center justify-center bg-[#07080a] px-5 text-white"><div className="w-full max-w-md rounded-3xl border border-white/10 bg-white/[0.03] p-7"><div className="text-xs font-semibold uppercase tracking-[0.25em] text-emerald-400">ResoFit Digital Factory</div><h1 className="mt-3 text-2xl font-semibold">Create account</h1><p className="mt-2 text-sm text-white/50">Create a ResoFit account. Production-factory access remains role-controlled.</p><form onSubmit={submit} className="mt-6 space-y-3"><input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email address" autoComplete="email" className="w-full rounded-xl border border-white/10 bg-black/30 px-3 py-3 text-sm outline-none"/><input required minLength={8} type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password (8+ characters)" autoComplete="new-password" className="w-full rounded-xl border border-white/10 bg-black/30 px-3 py-3 text-sm outline-none"/><input required minLength={8} type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} placeholder="Confirm password" autoComplete="new-password" className="w-full rounded-xl border border-white/10 bg-black/30 px-3 py-3 text-sm outline-none"/><button disabled={busy} className="w-full rounded-xl bg-white px-4 py-3 text-sm font-semibold text-black disabled:opacity-50">{busy?"Creating…":"Create account"}</button></form>{message&&<p className="mt-4 rounded-xl border border-amber-400/20 bg-amber-400/5 p-3 text-xs text-amber-200">{message}</p>}<div className="mt-5 flex justify-between text-xs text-white/55"><Link to="/login" className="hover:text-white">Sign in</Link><Link to="/forgot-password" className="hover:text-white">Forgot password?</Link></div></div></main>;
}
