import { createFileRoute } from "@tanstack/react-router";
import { createClient } from "@supabase/supabase-js";

const GEMINI_BASE = "https://generativelanguage.googleapis.com/v1beta";
const VIDEO_MODEL = "veo-3.1-generate-preview";
const IMAGE_MODEL = "gemini-3.1-flash-image";
const BUCKET = "digital-product-media";

export const maxDuration = 300;

function env(name: string) {
  const value = process.env[name];
  if (!value) throw new Error(`${name}_missing`);
  return value;
}

function db() {
  return createClient(env("VITE_SUPABASE_URL"), env("SUPABASE_SERVICE_ROLE_KEY"), {
    auth: { persistSession: false, autoRefreshToken: false },
  });
}

async function requireAdmin(request: Request) {
  const authorization = request.headers.get("authorization") ?? "";
  if (!authorization.startsWith("Bearer ")) throw new Error("unauthorized");
  const client = db();
  const { data: { user } } = await client.auth.getUser(authorization.slice(7));
  if (!user) throw new Error("unauthorized");
  const { data: roles } = await client.from("user_roles").select("role").eq("user_id", user.id);
  const allowed = (user.email ?? "").toLowerCase() === "ceo@resofit.fit" ||
    (roles ?? []).some((r: { role?: string }) => ["admin", "moderator"].includes(String(r.role ?? "")));
  if (!allowed) throw new Error("forbidden");
  return { client, user };
}

async function upload(client: ReturnType<typeof db>, path: string, bytes: Uint8Array, mime: string) {
  const bucket = client.storage.from(BUCKET);
  const result = await bucket.upload(path, bytes, { contentType: mime, upsert: true });
  if (result.error) {
    const created = await client.storage.createBucket(BUCKET, { public: true, fileSizeLimit: 524288000 });
    if (created.error && !/already exists/i.test(created.error.message)) throw created.error;
    const retry = await bucket.upload(path, bytes, { contentType: mime, upsert: true });
    if (retry.error) throw retry.error;
  }
  return bucket.getPublicUrl(path).data.publicUrl;
}

async function register(client: ReturnType<typeof db>, job: any, slot: any, bytes: Uint8Array, mime: string, sourceId: string) {
  const path = `${job.product_sku}/v${job.version}/${slot.role}.${mime === "video/mp4" ? "mp4" : "png"}`;
  const url = await upload(client, path, bytes, mime);
  const video = mime === "video/mp4";
  const { data: asset, error } = await client.from("content_asset_registry").upsert({
    source_provider: "gemini_api",
    source_asset_id: sourceId,
    source_url: url,
    canonical_url: url,
    brand: "ResoFlex",
    campaign: "digital_product_factory",
    asset_type: video ? "video" : "image",
    mime_type: mime,
    rights_status: "gemini_api_generated",
    commercial_status: "factory_generated",
    qa_status: "pending",
    qa_reason: "Generated by the production Digital Product Factory; existing ChatB2K/Gemini QA required.",
    content_pillar: "DIGITAL_PRODUCT",
    intelligence: {
      factory_job_id: job.id,
      product_sku: job.product_sku,
      role: slot.role,
      media_origin: video ? "Google Gemini API / Veo 3.1" : "Google Gemini API / Gemini 3.1 Flash Image",
      generation_version: job.version,
      canonical_destination: `https://www.resofit.fit/product/${job.generation_spec?.product?.handle ?? job.product_sku}`,
    },
    verified_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  }, { onConflict: "source_provider,source_asset_id" }).select("id,canonical_url,asset_type,qa_status").single();
  if (error) throw error;
  await client.from("digital_product_factory_assets").upsert({
    job_id: job.id, content_asset_id: asset.id, role: slot.role, required: !!slot.required, status: "attached",
  }, { onConflict: "job_id,content_asset_id,role" });
  return asset;
}

async function startVideo(key: string, slot: any) {
  const response = await fetch(`${GEMINI_BASE}/models/${VIDEO_MODEL}:predictLongRunning`, {
    method: "POST",
    headers: { "x-goog-api-key": key, "content-type": "application/json" },
    body: JSON.stringify({
      instances: [{ prompt: slot.prompt }],
      parameters: { aspectRatio: slot.aspect_ratio, durationSeconds: Number(slot.duration_seconds ?? 8), resolution: "720p", numberOfVideos: 1 },
    }),
  });
  const body = await response.json();
  if (!response.ok || !body.name) throw new Error(`veo_submit_failed:${response.status}`);
  return body.name as string;
}

async function generateImage(key: string, slot: any) {
  const response = await fetch(`${GEMINI_BASE}/interactions`, {
    method: "POST",
    headers: { "x-goog-api-key": key, "content-type": "application/json" },
    body: JSON.stringify({
      model: IMAGE_MODEL,
      input: [{ type: "text", text: slot.prompt }],
      response_format: { type: "image", mime_type: "image/png", aspect_ratio: slot.aspect_ratio, image_size: "2K" },
    }),
  });
  const body = await response.json();
  if (!response.ok || !body?.output_image?.data) throw new Error(`image_generation_failed:${response.status}`);
  return Uint8Array.from(Buffer.from(body.output_image.data, "base64"));
}

async function pollVideo(key: string, operationName: string) {
  const response = await fetch(`${GEMINI_BASE}/${operationName}`, { headers: { "x-goog-api-key": key } });
  const body = await response.json();
  if (!response.ok) throw new Error("veo_poll_failed");
  if (!body.done) return null;
  if (body.error) throw new Error("veo_generation_failed");
  const uri = body?.response?.generateVideoResponse?.generatedSamples?.[0]?.video?.uri;
  if (!uri) throw new Error("veo_output_missing");
  const video = await fetch(uri, { headers: { "x-goog-api-key": key } });
  if (!video.ok) throw new Error("veo_download_failed");
  return new Uint8Array(await video.arrayBuffer());
}

export const Route = createFileRoute("/api/digital-product-media-generator")({
  server: {
    handlers: {
      POST: async ({ request }) => {
        try {
          const { client } = await requireAdmin(request);
          const key = env("GEMINI_API_KEY");
          const body = await request.json().catch(() => ({}));
          const action = String(body.action ?? "status");
          const jobId = String(body.job_id ?? "1c6c9196-77fe-48ce-92c7-1429c9bf79ef");
          const { data: job, error } = await client.from("digital_product_factory_jobs").select("*").eq("id", jobId).maybeSingle();
          if (error || !job) return Response.json({ ok: false, error: "job_not_found" }, { status: 404 });
          const spec = structuredClone(job.generation_spec ?? {});

          if (action === "start") {
            const slots = spec.asset_slots ?? [];
            for (const slot of slots) {
              if (slot.runtime?.status) continue;
              slot.runtime = { status: "generating", started_at: new Date().toISOString(), model: slot.type === "video" ? VIDEO_MODEL : IMAGE_MODEL };
              if (slot.type === "video") {
                slot.runtime.operation_name = await startVideo(key, slot);
                slot.runtime.status = "submitted";
              } else {
                const bytes = await generateImage(key, slot);
                const asset = await register(client, job, slot, bytes, "image/png", `${job.id}:${slot.role}:v${job.version}`);
                slot.runtime = { status: "completed", asset_id: asset.id };
              }
              await client.from("digital_product_factory_jobs").update({ generation_spec: spec, status: "generating", updated_at: new Date().toISOString() }).eq("id", job.id);
            }
            return Response.json({ ok: true, status: "generating", generation_spec: spec });
          }

          if (action === "poll") {
            const results: any[] = [];
            for (const slot of spec.asset_slots ?? []) {
              if (slot.type !== "video" || slot.runtime?.status !== "submitted") continue;
              const bytes = await pollVideo(key, slot.runtime.operation_name);
              if (!bytes) { results.push({ role: slot.role, status: "pending" }); continue; }
              const asset = await register(client, job, slot, bytes, "video/mp4", `${job.id}:${slot.role}:v${job.version}`);
              slot.runtime = { status: "completed", asset_id: asset.id };
              results.push({ role: slot.role, status: "completed", asset_id: asset.id });
            }
            const completed = (spec.asset_slots ?? []).filter((s: any) => s.runtime?.status === "completed").length;
            const failed = (spec.asset_slots ?? []).filter((s: any) => s.runtime?.status === "failed").length;
            await client.from("digital_product_factory_jobs").update({ generation_spec: spec, asset_count: completed, status: failed ? "failed" : completed === (spec.asset_slots ?? []).length ? "qa" : "generating", updated_at: new Date().toISOString() }).eq("id", job.id);
            return Response.json({ ok: true, completed, total: (spec.asset_slots ?? []).length, results });
          }

          return Response.json({ ok: true, status: job.status, generation_spec: spec, assets: job.asset_count, approved: job.approved_asset_count });
        } catch (error) {
          const message = error instanceof Error ? error.message : String(error);
          const status = message === "unauthorized" ? 401 : message === "forbidden" ? 403 : 500;
          return Response.json({ ok: false, error: message }, { status });
        }
      },
    },
  },
});